// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smdrhuuvlecshmpwyzxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtZHJodXV2bGVjc2htcHd5enhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MzE0MjksImV4cCI6MjA3MjMwNzQyOX0.8hj5wysz6Klrtev_Ig2-geLYBLQiKeW3GQcp_tWS0X8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});